data = {
    "href": "https://api.spotify.com/v1/playlists/13Y6dl6F2USjAmgMs7d763/tracks?offset=0&limit=100",
    "items": [
        {
            "added_at": "2020-02-07T00:05:22Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                            },
                            "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                            "id": "52zMTJCKluDlFwMQWmccY7",
                            "name": "LOONA",
                            "type": "artist",
                            "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "KW",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "SA",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6rOL2mghTfDyx5CY0eU1Dn"
                    },
                    "href": "https://api.spotify.com/v1/albums/6rOL2mghTfDyx5CY0eU1Dn",
                    "id": "6rOL2mghTfDyx5CY0eU1Dn",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27313fa1b29c6c48aaf925d3ae1",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0213fa1b29c6c48aaf925d3ae1",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485113fa1b29c6c48aaf925d3ae1",
                            "width": 64
                        }
                    ],
                    "name": "[#]",
                    "release_date": "2020-02-05",
                    "release_date_precision": "day",
                    "total_tracks": 6,
                    "type": "album",
                    "uri": "spotify:album:6rOL2mghTfDyx5CY0eU1Dn"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                        },
                        "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                        "id": "52zMTJCKluDlFwMQWmccY7",
                        "name": "LOONA",
                        "type": "artist",
                        "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "SA",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 66200,
                "episode": False,
                "explicit": False,
                "external_ids": {
                    "isrc": "KRA382000124"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/3Q4eFdGe02tM0whH8AH4F0"
                },
                "href": "https://api.spotify.com/v1/tracks/3Q4eFdGe02tM0whH8AH4F0",
                "id": "3Q4eFdGe02tM0whH8AH4F0",
                "is_local": False,
                "name": "#",
                "popularity": 50,
                "preview_url": "https://p.scdn.co/mp3-preview/1d63811057ed825023e6ecd0d3def5a53b5042a1?cid=835cea40f4bd4eec8809798ee62f1cf9",
                "track": True,
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:3Q4eFdGe02tM0whH8AH4F0"
            },
            "video_thumbnail": {
                "url": None
            }
        },
        {
            "added_at": "2020-02-07T00:05:22Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                            },
                            "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                            "id": "52zMTJCKluDlFwMQWmccY7",
                            "name": "LOONA",
                            "type": "artist",
                            "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "KW",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "SA",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6rOL2mghTfDyx5CY0eU1Dn"
                    },
                    "href": "https://api.spotify.com/v1/albums/6rOL2mghTfDyx5CY0eU1Dn",
                    "id": "6rOL2mghTfDyx5CY0eU1Dn",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27313fa1b29c6c48aaf925d3ae1",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0213fa1b29c6c48aaf925d3ae1",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485113fa1b29c6c48aaf925d3ae1",
                            "width": 64
                        }
                    ],
                    "name": "[#]",
                    "release_date": "2020-02-05",
                    "release_date_precision": "day",
                    "total_tracks": 6,
                    "type": "album",
                    "uri": "spotify:album:6rOL2mghTfDyx5CY0eU1Dn"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                        },
                        "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                        "id": "52zMTJCKluDlFwMQWmccY7",
                        "name": "LOONA",
                        "type": "artist",
                        "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "SA",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 198040,
                "episode": False,
                "explicit": False,
                "external_ids": {
                    "isrc": "KRA382000125"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/7w3pIUjz7BTTqj9uAws40m"
                },
                "href": "https://api.spotify.com/v1/tracks/7w3pIUjz7BTTqj9uAws40m",
                "id": "7w3pIUjz7BTTqj9uAws40m",
                "is_local": False,
                "name": "So What",
                "popularity": 67,
                "preview_url": "https://p.scdn.co/mp3-preview/9865a2f52fa5928dd85327bb5d55e76026dfd4a9?cid=835cea40f4bd4eec8809798ee62f1cf9",
                "track": True,
                "track_number": 2,
                "type": "track",
                "uri": "spotify:track:7w3pIUjz7BTTqj9uAws40m"
            },
            "video_thumbnail": {
                "url": None
            }
        },
        {
            "added_at": "2020-02-07T00:05:22Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                            },
                            "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                            "id": "52zMTJCKluDlFwMQWmccY7",
                            "name": "LOONA",
                            "type": "artist",
                            "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "KW",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "SA",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6rOL2mghTfDyx5CY0eU1Dn"
                    },
                    "href": "https://api.spotify.com/v1/albums/6rOL2mghTfDyx5CY0eU1Dn",
                    "id": "6rOL2mghTfDyx5CY0eU1Dn",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27313fa1b29c6c48aaf925d3ae1",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0213fa1b29c6c48aaf925d3ae1",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485113fa1b29c6c48aaf925d3ae1",
                            "width": 64
                        }
                    ],
                    "name": "[#]",
                    "release_date": "2020-02-05",
                    "release_date_precision": "day",
                    "total_tracks": 6,
                    "type": "album",
                    "uri": "spotify:album:6rOL2mghTfDyx5CY0eU1Dn"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                        },
                        "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                        "id": "52zMTJCKluDlFwMQWmccY7",
                        "name": "LOONA",
                        "type": "artist",
                        "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "SA",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 202946,
                "episode": False,
                "explicit": False,
                "external_ids": {
                    "isrc": "KRA382000126"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/2GGzUBEJE1dN2PHrf7neS7"
                },
                "href": "https://api.spotify.com/v1/tracks/2GGzUBEJE1dN2PHrf7neS7",
                "id": "2GGzUBEJE1dN2PHrf7neS7",
                "is_local": False,
                "name": "Number 1",
                "popularity": 52,
                "preview_url": "https://p.scdn.co/mp3-preview/5ea770428ac5394a9d4c56f9c4adbece64f6577e?cid=835cea40f4bd4eec8809798ee62f1cf9",
                "track": True,
                "track_number": 3,
                "type": "track",
                "uri": "spotify:track:2GGzUBEJE1dN2PHrf7neS7"
            },
            "video_thumbnail": {
                "url": None
            }
        },
        {
            "added_at": "2020-02-07T00:05:22Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                            },
                            "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                            "id": "52zMTJCKluDlFwMQWmccY7",
                            "name": "LOONA",
                            "type": "artist",
                            "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "KW",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "SA",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6rOL2mghTfDyx5CY0eU1Dn"
                    },
                    "href": "https://api.spotify.com/v1/albums/6rOL2mghTfDyx5CY0eU1Dn",
                    "id": "6rOL2mghTfDyx5CY0eU1Dn",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27313fa1b29c6c48aaf925d3ae1",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0213fa1b29c6c48aaf925d3ae1",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485113fa1b29c6c48aaf925d3ae1",
                            "width": 64
                        }
                    ],
                    "name": "[#]",
                    "release_date": "2020-02-05",
                    "release_date_precision": "day",
                    "total_tracks": 6,
                    "type": "album",
                    "uri": "spotify:album:6rOL2mghTfDyx5CY0eU1Dn"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                        },
                        "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                        "id": "52zMTJCKluDlFwMQWmccY7",
                        "name": "LOONA",
                        "type": "artist",
                        "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "SA",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 195786,
                "episode": False,
                "explicit": False,
                "external_ids": {
                    "isrc": "KRA382000127"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/0WdCXlXSSfpIldlzZ4BrHi"
                },
                "href": "https://api.spotify.com/v1/tracks/0WdCXlXSSfpIldlzZ4BrHi",
                "id": "0WdCXlXSSfpIldlzZ4BrHi",
                "is_local": False,
                "name": "Oh (Yes I Am)",
                "popularity": 55,
                "preview_url": "https://p.scdn.co/mp3-preview/ff2ca4b09903be95ea027550e86379c7819460c2?cid=835cea40f4bd4eec8809798ee62f1cf9",
                "track": True,
                "track_number": 4,
                "type": "track",
                "uri": "spotify:track:0WdCXlXSSfpIldlzZ4BrHi"
            },
            "video_thumbnail": {
                "url": None
            }
        },
        {
            "added_at": "2020-02-07T00:05:22Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                            },
                            "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                            "id": "52zMTJCKluDlFwMQWmccY7",
                            "name": "LOONA",
                            "type": "artist",
                            "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "KW",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "SA",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6rOL2mghTfDyx5CY0eU1Dn"
                    },
                    "href": "https://api.spotify.com/v1/albums/6rOL2mghTfDyx5CY0eU1Dn",
                    "id": "6rOL2mghTfDyx5CY0eU1Dn",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27313fa1b29c6c48aaf925d3ae1",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0213fa1b29c6c48aaf925d3ae1",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485113fa1b29c6c48aaf925d3ae1",
                            "width": 64
                        }
                    ],
                    "name": "[#]",
                    "release_date": "2020-02-05",
                    "release_date_precision": "day",
                    "total_tracks": 6,
                    "type": "album",
                    "uri": "spotify:album:6rOL2mghTfDyx5CY0eU1Dn"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                        },
                        "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                        "id": "52zMTJCKluDlFwMQWmccY7",
                        "name": "LOONA",
                        "type": "artist",
                        "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "SA",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 178773,
                "episode": False,
                "explicit": False,
                "external_ids": {
                    "isrc": "KRA382000128"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/4bPY0n3hMVd6q39B2ePkZe"
                },
                "href": "https://api.spotify.com/v1/tracks/4bPY0n3hMVd6q39B2ePkZe",
                "id": "4bPY0n3hMVd6q39B2ePkZe",
                "is_local": False,
                "name": "Ding Ding Dong",
                "popularity": 50,
                "preview_url": "https://p.scdn.co/mp3-preview/1f0e09e72b74b1db9958e26b1f7dc39fb7621aff?cid=835cea40f4bd4eec8809798ee62f1cf9",
                "track": True,
                "track_number": 5,
                "type": "track",
                "uri": "spotify:track:4bPY0n3hMVd6q39B2ePkZe"
            },
            "video_thumbnail": {
                "url": None
            }
        },
        {
            "added_at": "2020-02-07T00:05:22Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                            },
                            "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                            "id": "52zMTJCKluDlFwMQWmccY7",
                            "name": "LOONA",
                            "type": "artist",
                            "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "KW",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "SA",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6rOL2mghTfDyx5CY0eU1Dn"
                    },
                    "href": "https://api.spotify.com/v1/albums/6rOL2mghTfDyx5CY0eU1Dn",
                    "id": "6rOL2mghTfDyx5CY0eU1Dn",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27313fa1b29c6c48aaf925d3ae1",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0213fa1b29c6c48aaf925d3ae1",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485113fa1b29c6c48aaf925d3ae1",
                            "width": 64
                        }
                    ],
                    "name": "[#]",
                    "release_date": "2020-02-05",
                    "release_date_precision": "day",
                    "total_tracks": 6,
                    "type": "album",
                    "uri": "spotify:album:6rOL2mghTfDyx5CY0eU1Dn"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7"
                        },
                        "href": "https://api.spotify.com/v1/artists/52zMTJCKluDlFwMQWmccY7",
                        "id": "52zMTJCKluDlFwMQWmccY7",
                        "name": "LOONA",
                        "type": "artist",
                        "uri": "spotify:artist:52zMTJCKluDlFwMQWmccY7"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "SA",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 221933,
                "episode": False,
                "explicit": False,
                "external_ids": {
                    "isrc": "KRA381905155"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/3AAu0viADpL0jFsRzOrlmR"
                },
                "href": "https://api.spotify.com/v1/tracks/3AAu0viADpL0jFsRzOrlmR",
                "id": "3AAu0viADpL0jFsRzOrlmR",
                "is_local": False,
                "name": "365",
                "popularity": 44,
                "preview_url": "https://p.scdn.co/mp3-preview/26e36fbedc9e7f252d0fdddc5acd8e565f52163e?cid=835cea40f4bd4eec8809798ee62f1cf9",
                "track": True,
                "track_number": 6,
                "type": "track",
                "uri": "spotify:track:3AAu0viADpL0jFsRzOrlmR"
            },
            "video_thumbnail": {
                "url": None
            }
        },
        {
            "added_at": "2020-02-07T00:05:31Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/uy6wcttkt4ycnqhe7gynrl3rq"
                },
                "href": "https://api.spotify.com/v1/users/uy6wcttkt4ycnqhe7gynrl3rq",
                "id": "uy6wcttkt4ycnqhe7gynrl3rq",
                "type": "user",
                "uri": "spotify:user:uy6wcttkt4ycnqhe7gynrl3rq"
            },
            "is_local": False,
            "primary_color": None,
            "track": None,
            "video_thumbnail": None
        }
    ],
    "limit": 100,
    "next": None,
    "offset": 0,
    "previous": None,
    "total": 7
}

print(data['next'])
data = data['items']

for i in range(len(data)-1):
    print(data[i]['track']['name'], data[i]['track']['artists'][0]['name'], data[i]['track']['id'])
